{% set name = "itemloaders" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fc2307f984116b010d6101a68a6a133ac8de927320b0ab696f31ad710a8d8d98

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    # Same order as setup.py:
    - w3lib >=1.17.0
    - parsel >=1.5.0
    - jmespath >=0.9.5
    - itemadapter >=0.1.0

test:
  imports:
    - itemloaders
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/scrapy/itemadapter
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Collect data from HTML and XML sources
  description: |
    Library that helps you collect data from HTML and XML sources.

extra:
  recipe-maintainers:
    - Gallaecio
    - wRAR
    - dangra
    - rmax
