{% set name = "itemloaders" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e6feec5e44e92e1931dbd70fce4da430491ee4cbc9a93a725351e4f0d614a411

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    # Same order as setup.py:
    - parsel >=1.5.0
    - jmespath >=0.9.5
    - itemadapter >=0.1.0

test:
  imports:
    - itemloaders
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - itemloaders
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/scrapy/itemloaders
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Collect data from HTML and XML sources
  description: |
    Library that helps you collect data from HTML and XML sources.

extra:
  recipe-maintainers:
    - Gallaecio
    - wRAR
    - dangra
    - rmax
