{% set name = "itemloaders" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4faf5b3abe83bf014476e3fd9ccf66867282971d9f1d4e96d9a61b60c3786770

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    # Same order as setup.py:
    - parsel >=1.5.0
    - jmespath >=0.9.5
    - itemadapter >=0.1.0

test:
  imports:
    - itemloaders
  requires:
    - pip
    - pytest
  source_files:
    - itemloaders
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/scrapy/itemloaders
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Collect data from HTML and XML sources
  description: |
    Library that helps you collect data from HTML and XML sources.

extra:
  recipe-maintainers:
    - Gallaecio
    - wRAR
    - dangra
    - rmax
